### ISSUE TITLE
 HTTP Error 400:

### ISSUE THREAD

**Issue by EA7JQA** [Buco7854/weewx-netatmo#2] opened 2024-03-18 20:32 UTC
Can somebody help me with this Error

mar 18 21:19:16 raspberrypi weewxd[904]: netatmo: netatmo-client: failed attempt 3 of 5 to get data: HTTP Error 400:
mar 18 21:19:16 raspberrypi weewxd[904]: netatmo: netatmo-client: waiting 10 seconds before retry
mar 18 21:19:26 raspberrypi weewxd[904]: netatmo: netatmo-client: url: https://api.netatmo.com/oauth2/token data: b'grant_type=refresh_token&refresh_token=INSERT_TOKEN_REFRESH&client_id=INSERT_CLI>
mar 18 21:19:27 raspberrypi weewxd[904]: netatmo: netatmo-client: failed attempt 4 of 5 to get data: HTTP Error 400:
mar 18 21:19:27 raspberrypi weewxd[904]: netatmo: netatmo-client: waiting 10 seconds before retry
mar 18 21:19:37 raspberrypi weewxd[904]: netatmo: netatmo-client: url: https://api.netatmo.com/oauth2/token data: b'grant_type=refresh_token&refresh_token=INSERT_TOKEN_REFRESH&client_id=INSERT_CLI>
mar 18 21:19:37 raspberrypi weewxd[904]: netatmo: netatmo-client: failed attempt 5 of 5 to get data: HTTP Error 400:
mar 18 21:19:37 raspberrypi weewxd[904]: netatmo: netatmo-client: waiting 10 seconds before retry
mar 18 21:19:47 raspberrypi weewxd[904]: netatmo: netatmo-client: failed to get data after 5 attempts
mar 18 21:19:47 raspberrypi weewxd[904]: netatmo: netatmo-client: next update in 300 seconds

**Comment by EB5TC** [comment] 2024-03-31 09:46
Entra en la web de Netatmo y refresca el token luego actualízalo en el config de weewx.
Log in Netatmo website and refresh the token, after that update in weewx config file.

**Comment by MrClever** [comment] 2024-06-06 05:55
I've noticed a new behaviour from the Netatmo's API. Once an access token is refreshed, it now returns BOTH an access and refresh token and Netatmo invalidate BOTH the previous tokens too.

This is a confirmed change in behaviour from Netatmo: https://helpcenter.netatmo.com/hc/en/community/posts/19350099833490/comments/19364475735314

What this means is, the `refresh_token` in the configuration becomes invalid after the first access token generated on application start! I did some testing and confirmed the following outside weewx:

1. if the *new* access **and** refresh tokens are stored somewhere (like updating a config file), then next time the code runs, the previous tokens will work.
2. if the access token has expired, the stored refresh token (from step 1) can request a new one. **THIS IS A ONE-SHOT DEAL** as once the new access token is returned, the stored refresh token is invalidated and the **new** refresh token that was handed back with the new access token becomes the *only* refresh token that will work.

So:
| Token | Behaviour |
|-------|--------|
| Refresh | Persistent until a `refresh_token` API call is made. After a `refresh_token` call is made the previous refresh token is invalid and ONLY the new refresh token can be used for the next `refresh_token` call. |
| Access | Ephemeral. These expire in 10800 seconds (*at time of writing*) or every 3 hours. After it expires a `refresh_token` call is required using a valid refresh token. |

So how this plays out in real life with weewx:
1. user creates an app and various ids/tokens at dev.netatmo.com - stores these in weewx.conf
2. user restarts weewx to pick up new config etc.
3. weewx-netatmo driver then fetches a new access token using the stored refresh token - this returns BOTH a new access token and refresh.
4. the access token is stored in memory and used until it expires, but the new refresh token is only stored in memory ([netatmo.py line 540](https://github.com/Buco7854/weewx-netatmo/blob/6c8329c1e03696200b4d1be17d451af830f62927/bin/user/netatmo.py#L540))
5. weewx-netatmo driver will refresh the expired access token after 3 hours but uses the in-memory refresh token.
6. once the app is restarted, the in-memory refresh token is lost and the one in the config file is invalid.

After step 3 - weewx-netatmo is doomed unless it stores and can recall from a restart the NEW refresh token. If the user restarts the service between step 3 and 5, the driver won't work because it's trying to generate an access token from the invalidated refresh token in the configuration file.

The **ONLY** fix is to go to dev.netatmo.com and generate a new refresh token, replace the old one in the config file, then restart weewx. HOWEVER, after the next restart, the same problem will occur.

**Comment by WiggyToo** [comment] 2024-06-10 11:26
Thanks for your work here - I came across the same problem, I created a new token and tested in in Reqbin, it worked only once then failed with Reqbin error 10023. I generated another new one, put it in Weewx.conf and restarted but that didn't see, to work, or I got the timing wrong or something, 

Jun 10 12:17:30 Weather weewxd: netatmo: netatmo-client: failed attempt 5 of 5 to get data: HTTP Error 400:

Last successful retrieval of data and upload to Weewx website was June 3rd  23:55 (GMT+1)

Following this with interest, it's becoming harder and harder to get the data from Netatmo sadly.

Gav

**Comment by WiggyToo** [comment] 2024-06-10 11:40
PS - repeated the above so getting data for now, thanks,

Gav

**Comment by WiggyToo** [comment] 2024-06-12 08:31
Further note - if, like me, for some reason you had a daily scheduled restart then your access to data will clearly fail after the restart, I have no recollection of adding this schedule but have removed it for now from the etc/crontab file.

Regards,
Gav

**Comment by Buco7854** [comment] 2024-06-24 09:41
Didn't have the notification enabled for the repo, I'll see what I can do later.

**Comment by Buco7854** [comment] 2024-06-24 10:02
> I've noticed a new behaviour from the Netatmo's API. Once an access token is refreshed, it now returns BOTH an access and refresh token and Netatmo invalidate BOTH the previous tokens too.
> 
> This is a confirmed change in behaviour from Netatmo: https://helpcenter.netatmo.com/hc/en/community/posts/19350099833490/comments/19364475735314
> 
> What this means is, the `refresh_token` in the configuration becomes invalid after the first access token generated on application start! I did some testing and confirmed the following outside weewx:
> 
> 1. if the *new* access **and** refresh tokens are stored somewhere (like updating a config file), then next time the code runs, the previous tokens will work.
> 2. if the access token has expired, the stored refresh token (from step 1) can request a new one. **THIS IS A ONE-SHOT DEAL** as once the new access token is returned, the stored refresh token is invalidated and the **new** refresh token that was handed back with the new access token becomes the *only* refresh token that will work.
> 
> So:
> | Token | Behaviour |
> |-------|--------|
> | Refresh | Persistent until a `refresh_token` API call is made. After a `refresh_token` call is made the previous refresh token is invalid and ONLY the new refresh token can be used for the next `refresh_token` call. |
> | Access | Ephemeral. These expire in 10800 seconds (*at time of writing*) or every 3 hours. After it expires a `refresh_token` call is required using a valid refresh token. |
> 
> So how this plays out in real life with weewx:
> 1. user creates an app and various ids/tokens at dev.netatmo.com - stores these in weewx.conf
> 2. user restarts weewx to pick up new config etc.
> 3. weewx-netatmo driver then fetches a new access token using the stored refresh token - this returns BOTH a new access token and refresh.
> 4. the access token is stored in memory and used until it expires, but the new refresh token is only stored in memory ([netatmo.py line 540](https://github.com/Buco7854/weewx-netatmo/blob/6c8329c1e03696200b4d1be17d451af830f62927/bin/user/netatmo.py#L540))
> 5. weewx-netatmo driver will refresh the expired access token after 3 hours but uses the in-memory refresh token.
> 6. once the app is restarted, the in-memory refresh token is lost and the one in the config file is invalid.
> 
> After step 3 - weewx-netatmo is doomed unless it stores and can recall from a restart the NEW refresh token. If the user restarts the service between step 3 and 5, the driver won't work because it's trying to generate an access token from the invalidated refresh token in the configuration file.
> 
> The **ONLY** fix is to go to dev.netatmo.com and generate a new refresh token, replace the old one in the config file, then restart weewx. HOWEVER, after the next restart, the same problem will occur.

I think i will just rewrite the token in the config on each refresh.

**Comment by Buco7854** [comment] 2024-06-24 19:40
Just pushed a fix. Please read the README for the new configuration. Basically `refresh_token` is not in config anymore and replaced by `tokens_persistence_file` you must pass the path to a json file that contain it so that the file is updated on each refresh. Make sur weewx has permissions.

**Comment by Buco7854** [comment] 2024-06-24 19:41
Waiting for some feedbacks before closing.

**Comment by MrClever** [comment] 2024-06-24 23:30
> Just pushed a fix. Please read the README for the new configuration. Basically `refresh_token` is not in config anymore and replaced by `tokens_persistence_file` you must pass the path to a json file that contain it so that the file is updated on each refresh. Make sur weewx has permissions.

My Weewx system is offline for the moment but I will be able to test in a few days. I assume the new token_persistence_file needs to be on a persistent file system to survive reboots (edit: read the README…you already explained this 🤦🏻‍♂️ I need more coffee!). Will report back once I’ve tested. Also thanks for the patch!

**Comment by WiggyToo** [comment] 2024-06-25 09:58
Just testing now - getting this error, can you provide an example of the file please just to make sure I have it correct?

Thanks

Jun 25 10:52:32 Weather weewx[11119] CRITICAL __main__:     ****      raise Exception(f"Could not decode {self._tokens_persistence_file} content into a json format, "
Jun 25 10:52:32 Weather weewx[11119] CRITICAL __main__:     ****                                                                                                     ^
Jun 25 10:52:32 Weather weewx[11119] CRITICAL __main__:     ****  SyntaxError: invalid syntax

I created it as a plain text file and put in one line as follows (including all the quotes) - the root user has access and is running the Weewx service, are there any other checks I should complete?

{"refresh_token": "my long number here - freshly generated from the Netatmo App site"}

CONF is as follows:

[netatmo]
    
    driver = user.netatmo
    grant_type = refresh_token
    refresh_token = [my long number]
    client_id = [my client ID]
    client_secret = [my client secret]
    username = INSERT_USERNAME_HERE
    password = INSERT_PASSWORD_HERE
    tokens_persistence_file = /etc/weewx/tokens_persistence_file.json

**Comment by Buco7854** [comment] 2024-06-25 10:26
> Just testing now - getting this error, can you provide an example of the file please just to make sure I have it correct?
> 
> Thanks
> 
> Jun 25 10:52:32 Weather weewx[11119] CRITICAL __main__:     ****      raise Exception(f"Could not decode {self._tokens_persistence_file} content into a json format, "
> Jun 25 10:52:32 Weather weewx[11119] CRITICAL __main__:     ****                                                                                                     ^
> Jun 25 10:52:32 Weather weewx[11119] CRITICAL __main__:     ****  SyntaxError: invalid syntax
> 
> I created it as a plain text file and put in one line as follows (including all the quotes) - the root user has access and is running the Weewx service, are there any other checks I should complete?
> 
> {"refresh_token": "my long number here - freshly generated from the Netatmo App site"}
> 
> CONF is as follows:
> 
> [netatmo]
>     
>     driver = user.netatmo
>     grant_type = refresh_token
>     refresh_token = [my long number]
>     client_id = [my client ID]
>     client_secret = [my client secret]
>     username = INSERT_USERNAME_HERE
>     password = INSERT_PASSWORD_HERE
>     tokens_persistence_file = /etc/weewx/tokens_persistence_file.json
> 

The file should be exactly as the example provided in the readme. I made an other push since your logs were weird and its maybe caused by a feature not present in your python version, could you try again?

**Comment by WiggyToo** [comment] 2024-06-25 10:45
Thanks - that is getting further, although I have to make this manual change to netatmo.py other I get this error reading the queue:

```
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 148, in main
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 81, in __init__
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****      self.setupStation(config_dict)
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 108, in setupStation
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****      __import__(driver)
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****    File "/usr/share/weewx/user/netatmo.py", line 27, in <module>
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****      import queue
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****  ImportError: No module named queue
Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****  Exiting.

```
I have had to do this before and no doubt relates to the Python version you mentioned I just change to comment out line 27 which throws an error on my setup

```
import queue
import sys

try:
    import queue as Queue  # Python 3
except:
    import Queue  # Python 2
```

to

```
#import queue
import sys

try:
    import queue as Queue  # Python 3
except:
    import Queue  # Python 2
```

I am now no longer getting the JSON file read error, so thanks for that - I am trying to generate new tokens on the Netatmo site but it is complaining about "invalid client" so will just need to sort that out and retest.

Regards,
Gav

**Comment by Buco7854** [comment] 2024-06-25 10:51
> Thanks - that is getting further, although I have to make this manual change to netatmo.py other I get this error reading the queue:
> 
> ```
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****    File "/usr/share/weewx/weewxd", line 148, in main
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****      engine = weewx.engine.StdEngine(config_dict)
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 81, in __init__
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****      self.setupStation(config_dict)
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****    File "/usr/share/weewx/weewx/engine.py", line 108, in setupStation
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****      __import__(driver)
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****    File "/usr/share/weewx/user/netatmo.py", line 27, in <module>
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****      import queue
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****  ImportError: No module named queue
> Jun 25 11:32:28 Weather weewx[11445] CRITICAL __main__:     ****  Exiting.
> ```
> 
> I have had to do this before and no doubt relates to the Python version you mentioned I just change to comment out line 27 which throws an error on my setup
> 
> ```
> import queue
> import sys
> 
> try:
>     import queue as Queue  # Python 3
> except:
>     import Queue  # Python 2
> ```
> 
> to
> 
> ```
> #import queue
> import sys
> 
> try:
>     import queue as Queue  # Python 3
> except:
>     import Queue  # Python 2
> ```
> 
> I am now no longer getting the JSON file read error, so thanks for that - I am trying to generate new tokens on the Netatmo site but it is complaining about "invalid client" so will just need to sort that out and retest.
> 
> Regards, Gav

I'm pretty sure the import queue is not even used so i just removed it.

If someone with a different setup could reinstall the extension just to be sure it would be perfect tho.

For the client thing I guess jsut double check the client id and secret. Make sure to regenerate a new token for the file after and I guess you should be good.

**Comment by WiggyToo** [comment] 2024-06-25 11:01
Thanks - getting closer, I still have a 400 error so the 3 tokens are out of sync somehow, I'll double check.

Can I delete the refresh token from the CONF file is it now gets it from the other file, in case there is a conflict?

Gav

**Comment by Buco7854** [comment] 2024-06-25 11:05
The one in the config file can be safely deleted. And yes, you may want to regenerate new credentials (id, secret, refresh token) so that you are sure everything is up to date.

**Comment by WiggyToo** [comment] 2024-06-25 11:26
Thanks for that - I am still getting a 400 error, it may be the order I am starting things or something. The process I have followed is to stop WEEWX then generate the refresh token. Put this in the persistence file, check that the ID and Secret are still OK.

Then start WEEWX, early in the log we get

```
Jun 25 12:11:48 Weather weewxd: netatmo: netatmo-client: url: https://api.netatmo.com/oauth2/token data: client_secret=[blah]&grant_type=refresh_token&client_id=[blah]&refresh_token=[blah]1 hdr: {'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8'}
```

Then the engine loads and the timer starts, 10 seconds after the event above it tries again and throws an error.

```

Jun 25 12:11:58 Weather weewxd: netatmo: netatmo-client: url: https://api.netatmo.com/oauth2/token data: client_secret=[blah]&grant_type=refresh_token&client_id=[blah]&refresh_token=[blah]1 hdr: {'Content-Type': 'application/x-www-form-urlencoded;charset=utf-8'}
Jun 25 12:11:58 Weather weewxd: netatmo: netatmo-client: failed attempt 2 of 5 to get data: HTTP Error 400:
Jun 25 12:11:58 Weather weewxd: netatmo: netatmo-client: waiting 10 seconds before retry

```
I'll have another go but I seem to be getting out of sequence somewhere so that when it tries to connect for the first time it has already expired the token,

Regards,
Gav

**Comment by Buco7854** [comment] 2024-06-25 11:39
Are you sure the driver is writing into the file? May be a permission issue so the driver cannot write and so it use the old token on the second try

**Comment by WiggyToo** [comment] 2024-06-25 11:47
Just checking it all now, I've created a new app on Netatmo, used Reqbin to confirm the refresh token is being generated and then if I post to Reqbin with the new refresh token I can see a new one being created, so I suspect my original Neatmo App had a problem.

I can see no 400 errors and I have generated a set of reports to my website so all good, I will just test it works all OK after a restart.

https://www.wiggytoo.co.uk/

Bit hot for this sort of work.

**Comment by WiggyToo** [comment] 2024-06-25 11:56
OK - restart testing complete, and data being retrieved and uploaded to site successfully.

Thanks for your hard work and patience, I'll monitor things but this is currently working on my setup.

Gav

**Comment by bucolo** [comment] 2024-06-25 12:14
It's ok for me too. 
you must not forget to do a : chown weewx:weewx /etc/weewx/tokens_persistence_file.json  after creating the file and having pasted the regenerated refresh_token
Thank you very much Buco7854

**Closed as completed** 2024-06-25 18:27 UTC

**Comment by WiggyToo** [comment] 2024-06-27 11:27
Just to add I have now moved to a new image with Debian 12 and Weewx 5 and tested on that platform, all works OK,
